export const data = {
    status: 1,
    data: [
        {
            id: "305",
            user_id: "130",
            name: "Conflict Of Interest",
            foregroundColor: "",
            localAvatarPath: "",
            filename: "playlist_1598035794108.jpg",
            songCount: 4,
            created_at: "2020-11-18 08:00:45",
            updated_at: "2020-08-22 02:46:36",
            playlist_status: "1",
            is_synced: "0",
            shared: "1",
            plays: "16",
            _id: "305",
            user: {
                id: "130",
                active: "1",
                user_type: "0",
                email: "tester@gmail.com",
                username: "tester",
                created_on: "0",
                first_name: "tester",
                last_name: "tester",
                date_of_birth: "1970-01-01",
                phone: "+19367079458",
                phone_verification_code: null,
                photo: "profile_1612288848211.png",
                gender: "0",
                social_id: "",
                social_type: null,
                social_link: null,
                address: "",
                full_name: "tester tester",
                token: "x9719R1pEdbk0RBgK0GoYuwhPfTSwxmDcm8oevLo4EF0av9Hop",
                following_count: "22",
                followers_count: "12",
                brief: "",
                back_image: "profile_back_1601877545383.png",
                plays: "6059",
                city: "",
                genre: "",
                race: "",
                address_line1: "",
                address_line2: "",
                postal_code: "",
                state: "",
                country_code: "",
                paypal_email: "",
                card_number: "",
                card_exp_month: "0",
                card_exp_year: "0",
                card_cvc: "",
                bank_account_number: "",
                currency: "",
                routing_number: "",
                account_holder_name: "",
                account_holder_type: "",
                id_number: "",
                ssn_last_4: "",
                document_front: "",
                document_back: "",
                streamed_count: 684,
                avatarURL: "http://192.168.10.216:31839/assets/uploads/profile/photo/profile_1612288848211.png",
                backImage: "http://192.168.10.216:31839/assets/uploads/profile/photo/profile_back_1601877545383.png",
                socketID: "x9719R1pEdbk0RBgK0GoYuwhPfTSwxmDcm8oevLo4EF0av9Hop",
                user_favorite_types: [
                    {
                        id: "9",
                        user_id: "130",
                        favorite_type_id: "3",
                        created_at: "0000-00-00 00:00:00"
                    }
                ]
            },
            remoteAvatarPath: "http://192.168.10.216:31839/assets/uploads/playlists/playlist_1598035794108.jpg",
            songs: [
                {
                    id: "2457",
                    playlist_id: "305",
                    song_id: "2700",
                    pos: "1",
                    created_at: "2020-08-21 18:46:36",
                    _id: "2457",
                    song: {
                        id: "2700",
                        title: "Between Me And You feat. Cardeair",
                        user_id: "1",
                        local_id: "0",
                        albumId: "271",
                        albumName: "Conflict Of Interest",
                        artistId: "90",
                        artistName: "DoubleCup Killa",
                        ISRC: "",
                        writer: "",
                        Produced_By: "",
                        Label: "",
                        Performed_By: "",
                        duration: "1",
                        trackNumber: "0",
                        localPath: "",
                        file: "song_1597882558586.mp3",
                        created_at: "2022-03-20 23:05:27",
                        plays: "23",
                        number: "0",
                        media_link: "https://crowdded.s3.us-east-2.amazonaws.com/song_1597882558586.mp3",
                        remotePath: "http://192.168.10.216:31839/assets/uploads/songs/song_1597882558586.mp3"
                    }
                }
            ]
        }
    ]
}